version: "3"
networks:
  ibm:
    driver: bridge
  oracle:
    driver: bridge
services:
  web:
    image: nginx
    container_name: my-nginx
    networks:
     - ibm
    ports:
     - 80
  database:
      networks:
        - oracle
      image: redis
      container_name: my-db
